-- SCHEMA TO CREATE THE USERTABLE
CREATE TABLE "IOT_ENERGYGRID_TABLE"
(
  "Serial No" INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE NO CYCLE NO CACHE ORDER),
  "Current_ToGrid" FLOAT NOT NULL,
  "Current_SolarSupply" FLOAT NOT NULL,
  "Current_GridSupply" FLOAT NOT NULL,
  "Energy_ToGrid" FLOAT NOT NULL,
  "Energy2_SolarSupply" FLOAT NOT NULL,
  "Energy3_GridSupply" FLOAT NOT NULL,
  "TotalEnergy" FLOAT NOT NULL,
  "Time" TIMESTAMP NOT NULL
)ORGANIZE BY ROW;
